-- Seed the 20 triathlon-focused strength exercises.
-- created_by = NULL means system/public exercises.

INSERT INTO exercises (name, category, muscle_groups, equipment, triathlon_benefit, instructions, demo_url, demo_type, is_public) VALUES

-- Swim
('Lat Pulldown',           'strength', ARRAY['lats','biceps','rear delts'],        'cable',      'Builds the lat pull-phase power that drives every freestyle stroke catch and pull.', 'Grip bar just outside shoulder width. Pull to upper chest, squeeze lats at bottom. Control the return.', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Close-Grip_Front_Lat_Pulldown/0.jpg', 'image', true),
('Single-Arm Dumbbell Row','strength', ARRAY['lats','rhomboids','rear delts'],      'dumbbell',   'Unilateral lat strength directly mirrors the asymmetric pulling motion of freestyle swimming.', 'Brace on a bench, row dumbbell to hip. Elbow stays close to torso. Full range of motion.', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bent_Over_One_Arm_Dumbbell_Row/0.jpg', 'image', true),
('Cable Face Pull',        'strength', ARRAY['rear delts','external rotators','traps'], 'cable',  'Maintains shoulder health and scapular stability — essential for high swim volume weeks.', 'Set cable at face height. Pull to forehead, elbows high, externally rotate at end range.', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Face_Pull/0.jpg', 'image', true),
('Pull-Up',                'strength', ARRAY['lats','biceps','core'],               'bodyweight', 'Bodyweight pulling standard. Strong pull-ups directly transfer to swim stroke efficiency.', 'Dead hang start. Pull chin over bar leading with chest. Full lockout on each rep.', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Chin-Up/0.jpg', 'image', true),
('TRX Suspension Row',     'strength', ARRAY['lats','rhomboids','core'],            'bodyweight', 'Reinforces swim-specific pulling pattern under fatigue with scalable difficulty.', 'Lean back, body straight. Pull chest to handles, squeeze shoulder blades. The more horizontal, the harder.', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bent_Over_Two_Dumbbell_Row/0.jpg', 'image', true),

-- Bike
('Bulgarian Split Squat',  'strength', ARRAY['quads','glutes','hip flexors'],       'dumbbell',   'Unilateral quad and glute strength that maps directly to the single-leg pedal stroke.', 'Rear foot elevated on bench. Descend until rear knee nearly touches floor. Drive through front heel.', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bulgarian_Split_Squat/0.jpg', 'image', true),
('Barbell Hip Thrust',     'strength', ARRAY['glutes','hamstrings'],                'barbell',    'Maximises peak glute force in hip extension — the power phase of every pedal stroke.', 'Upper back on bench, bar across hips. Drive hips to full extension. Squeeze glutes at top.', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Hip_Thrust/0.jpg', 'image', true),
('Romanian Deadlift',      'strength', ARRAY['hamstrings','glutes','erectors'],     'barbell',    'Posterior chain resilience for long cycling hours and injury prevention on the run.', 'Hinge at hips with soft knees, bar stays close to legs. Feel hamstring stretch, drive hips forward to return.', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Romanian_Deadlift/0.jpg', 'image', true),
('Leg Press',              'strength', ARRAY['quads','glutes'],                     'machine',    'High quad volume without spinal load — ideal during heavy bike training blocks.', 'Feet hip-width at mid-plate. Control descent to 90°, press through heels. Don''t lock knees at top.', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leg_Press/0.jpg', 'image', true),

-- Run
('Nordic Hamstring Curl',      'strength', ARRAY['hamstrings'],                       'bodyweight', 'The #1 evidence-based exercise for hamstring injury prevention in runners.', 'Kneel with feet anchored. Slowly lower torso toward floor under control. Push off to return.', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Seated_Calf_Raise/0.jpg', 'image', true),
('Single-Leg Romanian Deadlift','strength', ARRAY['hamstrings','glutes','hip abductors'],'dumbbell','Hip stability in single-leg stance — mirrors run gait and prevents lateral drop.', 'Standing on one leg, hinge forward with dumbbell in opposite hand. Keep hips square throughout.', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Romanian_Deadlift/0.jpg', 'image', true),
('Box Step-Up',                'strength', ARRAY['quads','glutes','hip flexors'],     'dumbbell',   'Mimics run knee drive and trains eccentric deceleration — reduces impact injury risk.', 'Step onto box with full foot contact. Drive through heel to stand. Step down with control.', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Step_Ups/0.jpg', 'image', true),
('Single-Leg Calf Raise',      'strength', ARRAY['gastrocnemius','soleus'],           'bodyweight', 'Achilles load tolerance and calf strength are critical for run economy and injury prevention.', 'Stand on one leg on edge of step. Lower heel below step level, raise to full plantar flexion.', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Calf_Raise_On_A_Dumbbell/0.jpg', 'image', true),

-- Base strength
('Conventional Deadlift',  'strength', ARRAY['glutes','hamstrings','erectors','traps'], 'barbell', 'Total posterior chain force production — the foundation that supports all three sports.', 'Hip-width stance. Bar over mid-foot. Hinge and grip, brace hard, drive floor away. Lock out hips and knees.', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Deadlift/0.jpg', 'image', true),
('Back Squat',             'strength', ARRAY['quads','glutes','hamstrings'],           'barbell',   'Bilateral lower-body strength foundation. Peak power output transfers to bike and run.', 'Bar on upper traps. Squat to at least parallel. Knees track toes. Drive through full foot.', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Squat/0.jpg', 'image', true),
('Overhead Press',         'strength', ARRAY['deltoids','triceps','upper traps'],      'barbell',   'Shoulder girdle integrity for high swim volume. Protects rotator cuff under fatigue.', 'Bar at collarbone. Brace core, press vertically overhead. Full lockout. Lower under control.', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Shoulder_Press/0.jpg', 'image', true),
('Front Squat',            'strength', ARRAY['quads','core','upper back'],             'barbell',   'Upright torso posture mirrors TT aero position. Builds quad strength with core demand.', 'Bar in front rack position. Elbows high throughout. Squat to depth with vertical torso.', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Front_Barbell_Squat/0.jpg', 'image', true),

-- Core / stability
('Pallof Press',               'strength', ARRAY['obliques','transverse abdominis','glutes'], 'cable',     'Anti-rotation core stability — underpins efficient power transfer in all three disciplines.', 'Cable at chest height, stand sideways. Press straight out and hold 2s, resist rotation. Return slowly.', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Seated_Calf_Raise/0.jpg', 'image', true),
('Copenhagen Adductor Hold',   'strength', ARRAY['adductors','hip flexors'],                 'bodyweight', 'Hip adductor loading prevents groin injuries that frequently derail run-heavy training blocks.', 'Top leg on bench, bottom leg hanging. Lift bottom leg to meet top leg. Hold 3–5s, lower.', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Adductor/0.jpg', 'image', true),
('Dead Bug',                   'strength', ARRAY['transverse abdominis','diaphragm','hip flexors'], 'none', 'Lumbar spine stability under contralateral limb movement — directly transfers to all three sports.', 'Lying on back, arms straight up, knees 90°. Slowly lower opposite arm/leg. Breathe throughout. Keep low back flat.', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dead_Bug/0.jpg', 'image', true);
